[project]
name = "big-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SyraxTarg", email = "maimiti.saint-marc@efrei.net" },
    { name = "Claire Sbaffe", email = "claire.sbaffe@efrei.net" }
]
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=1.7.2",
    "dotenv>=0.9.9",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[project.scripts]
big-data = "big_data:main"
generating-lake = "scripts.generating_lake:main"
bronze = "scripts.bronze:main"
data-cleaning = "scripts.data_cleaning:main"
silver = "scripts.silver:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
